### ISSUE TITLE
..

### ISSUE THREAD

**Issue by ghost** [XronoZ-create/epicgame_captcha#1]
..

**Comment by McIvanX** [comment]
> Удалось найти решение? У меня есть отдельное решение для авторизации через http, нашел как расшифровать и зашифровать xal в jwt тоекене авторизации. Но так же не могу авторизоваться, та же ошибка - не верный ответ. Если нужно могу скинуть.

Hey, could you give me your contact information, i am also tryna to find out how to solve the token n dat shit, its very fucked tbh. I need a lil bit of help
